import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useForm, useFieldArray, type Resolver } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { api } from '../../lib/axios';
import { toast } from 'sonner';
import { AsyncSelect } from '../../components/AsyncSelect'; 
import { CreateInvoiceSchema, type CreateInvoiceDTO } from "@erp/types";
import { Plus, Trash2,  Loader2 } from 'lucide-react';

export default function InvoiceCreate() {
  const navigate = useNavigate();
  const [isLoading, setIsLoading] = useState(false);

  const { register, control, handleSubmit, watch, setValue, formState: { errors } } = useForm<CreateInvoiceDTO>({
    resolver: zodResolver(CreateInvoiceSchema) as Resolver<CreateInvoiceDTO>,
    defaultValues: {
      number: undefined, // Will be generated by backend
      date: new Date().toISOString().split('T')[0],
      expiredDate: new Date(Date.now() + 14 * 86400000).toISOString().split('T')[0],
      items: [{ itemName: '', description: '', quantity: 1, price: 0, total: 0 }],
      currency: 'USD', // Fallback default
      status: 'draft',
      paymentStatus: 'unpaid',
      taxRate: 0,
      discount: 0
    }
  });

  const { fields, append, remove } = useFieldArray({ control, name: "items" });

  const items = watch("items");
  const taxRate = watch("taxRate");
  const discount = watch("discount");
  const currency = watch("currency"); // Watch currency to display symbol
  
  // Calculations
  const calculatedSubTotal = items.reduce((sum, item) => sum + (item.quantity * item.price), 0);
  const calculatedTax = calculatedSubTotal * (taxRate / 100);
  const calculatedTotal = calculatedSubTotal + calculatedTax - discount;

  // ✅ FETCHERS (Scalable)
  const fetchClients = async (q: string) => (await api.get(`/clients?search=${q}&limit=20`)).data.data;
  const fetchProducts = async (q: string) => (await api.get(`/products?search=${q}&limit=20`)).data.data;

  // ✅ LOAD SETTINGS (Fixed: Now sets Currency)
  useEffect(() => {
    const loadSettings = async () => {
        try {
            const { data } = await api.get('/settings');
            const settings = data.data;
            if (settings) {
               if (settings.taxRate) setValue('taxRate', settings.taxRate);
               if (settings.defaultNotes) setValue('notes', settings.defaultNotes);
               
               // 👇 THIS LINE WAS MISSING
               if (settings.currency) setValue('currency', settings.currency); 

               if (settings.defaultPaymentTerms) {
                   const d = new Date();
                   d.setDate(d.getDate() + settings.defaultPaymentTerms);
                   setValue('expiredDate', d.toISOString().split('T')[0]);
               }
            }
        } catch (error) { console.error("Settings load failed"); }
    };
    loadSettings();
  }, [setValue]);

  const handleProductSelect = async (index: number, productId: string) => {
    if(!productId) return;
    try {
        const { data } = await api.get(`/products/${productId}`);
        const p = data.data;
        setValue(`items.${index}.itemName`, p.name);
        setValue(`items.${index}.description`, p.description || '');
        setValue(`items.${index}.price`, p.price);
        setValue(`items.${index}.quantity`, 1);
    } catch(e) { console.error(e); }
  };

  const onSubmit = async (data: CreateInvoiceDTO) => {
    setIsLoading(true);
    try {
      await api.post('/invoices', { 
          ...data, 
          subTotal: calculatedSubTotal,
          taxTotal: calculatedTax,
          total: calculatedTotal 
      });
      toast.success('Invoice created successfully!');
      navigate('/invoices');
    } catch (error: any) {
      toast.error(error.response?.data?.message || 'Creation failed');
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-gray-50 pb-12">
      <main className="max-w-5xl mx-auto p-6">
        <div className="flex justify-between items-center mb-6">
            <h1 className="text-3xl font-bold text-gray-900">New Invoice</h1>
        </div>

        <form onSubmit={handleSubmit(onSubmit)} className="bg-white p-8 rounded-xl shadow-sm border border-gray-200">
          
          {/* Top Section */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
            <div className="md:col-span-1">
              <AsyncSelect
                label="Client"
                placeholder="Search Client..."
                fetcher={fetchClients}
                renderOption={(c) => c.name}
                onChange={(id) => setValue('clientId', id, { shouldValidate: true })}
                error={errors.clientId?.message}
              />
            </div>

            <div>
                <label className="block text-sm font-medium mb-1 text-gray-700">Currency</label>
                <select {...register("currency")} className="w-full border p-2 rounded-lg bg-white focus:ring-2 focus:ring-blue-500 outline-none">
                    <option value="USD">USD ($)</option>
                    <option value="EUR">EUR (€)</option>
                    <option value="GBP">GBP (£)</option>
                    <option value="INR">INR (₹)</option>
                </select>
            </div>
            
            <div className="grid grid-cols-2 gap-3">
              <div>
                  <label className="block text-sm font-medium mb-1 text-gray-700">Date</label>
                  <input type="date" {...register("date")} className="w-full border p-2 rounded-lg outline-none" />
              </div>
              <div>
                  <label className="block text-sm font-medium mb-1 text-gray-700">Due Date</label>
                  <input type="date" {...register("expiredDate")} className="w-full border p-2 rounded-lg outline-none" />
              </div>
            </div>
          </div>

          {/* Items Section */}
          <div className="mb-8">
            <h3 className="font-semibold text-lg mb-4 text-gray-800">Invoice Items</h3>
            <div className="space-y-3">
                {fields.map((field, index) => (
                    <div key={field.id} className="flex flex-col md:flex-row gap-3 items-start bg-gray-50 p-4 rounded-lg border border-gray-100 group">
                        <div className="flex-1 w-full space-y-2">
                            <AsyncSelect
                                label="" 
                                placeholder="Select Product (Optional)"
                                fetcher={fetchProducts}
                                renderOption={(p) => `${p.name} - ${currency} ${p.price}`}
                                onChange={(id) => handleProductSelect(index, id)}
                            />
                            <div className="flex gap-2">
                                <input placeholder="Item Name" {...register(`items.${index}.itemName`)} className="flex-1 border p-2 rounded bg-white" />
                                <input placeholder="Description" {...register(`items.${index}.description`)} className="flex-1 border p-2 rounded bg-white text-sm" />
                            </div>
                            {errors.items?.[index]?.itemName && <span className="text-red-500 text-xs">Item name required</span>}
                        </div>
                        
                        <div className="flex gap-2 w-full md:w-auto">
                            <div className="w-20">
                                <input type="number" placeholder="Qty" {...register(`items.${index}.quantity`, { valueAsNumber: true })} className="w-full border p-2 rounded text-right" />
                            </div>
                            <div className="w-32">
                                <input type="number" step="0.01" placeholder="Price" {...register(`items.${index}.price`, { valueAsNumber: true })} className="w-full border p-2 rounded text-right" />
                            </div>
                            <button type="button" onClick={() => remove(index)} className="text-gray-400 hover:text-red-500 p-2"><Trash2 className="w-5 h-5" /></button>
                        </div>
                    </div>
                ))}
            </div>
            <button type="button" onClick={() => append({ itemName: '', description: '', quantity: 1, price: 0, total: 0 })} className="mt-4 text-blue-600 font-medium flex items-center gap-1 hover:text-blue-700">
                <Plus className="w-4 h-4" /> Add Line Item
            </button>
          </div>

          {/* Totals Section */}
          <div className="flex flex-col md:flex-row justify-end border-t pt-6 gap-12">
            <div className="w-full md:w-64 space-y-3">
                <div className="flex justify-between items-center text-sm">
                    <span className="text-gray-600">Subtotal</span>
                    <span className="font-medium">{calculatedSubTotal.toFixed(2)}</span>
                </div>
                
                <div className="flex justify-between items-center text-sm">
                    <span className="text-gray-600 flex items-center gap-1">Tax Rate (%)</span>
                    <input 
                        type="number" 
                        {...register("taxRate", { valueAsNumber: true })} 
                        className="w-16 border rounded p-1 text-right text-sm"
                    />
                </div>

                <div className="flex justify-between items-center text-sm">
                    <span className="text-gray-600">Discount</span>
                    <input 
                        type="number" 
                        {...register("discount", { valueAsNumber: true })} 
                        className="w-24 border rounded p-1 text-right text-sm"
                    />
                </div>

                <div className="flex justify-between items-center text-xl font-bold pt-3 border-t">
                    <span>Total ({currency})</span>
                    <span>{calculatedTotal.toFixed(2)}</span>
                </div>
            </div>
          </div>

          <div className="mt-8 flex justify-end gap-3">
            <button type="button" onClick={() => navigate('/invoices')} className="px-6 py-2 text-gray-600 hover:bg-gray-100 rounded-lg transition">Cancel</button>
            <button type="submit" disabled={isLoading} className="bg-black text-white px-8 py-3 rounded-lg font-bold hover:bg-gray-800 disabled:opacity-50 flex items-center gap-2">
                {isLoading && <Loader2 className="animate-spin w-4 h-4" />}
                {isLoading ? 'Creating...' : 'Create Invoice'}
            </button>
          </div>
        </form>
      </main>
    </div>
  );
}