service: flux-erp-api

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-2
  memorySize: 512
  timeout: 29
  environment:
    NODE_ENV: production
    MONGO_URI: ${param:MONGO_URI}
    JWT_SECRET: ${param:JWT_SECRET}
    CLERK_SECRET_KEY: ${param:CLERK_SECRET_KEY, ''}
    GROQ_API_KEY: ${param:GROQ_API_KEY, ''}
    SMTP_HOST: ${param:SMTP_HOST, 'smtp.ethereal.email'}
    SMTP_PORT: ${param:SMTP_PORT, '587'}
    SMTP_USER: ${param:SMTP_USER, ''}
    SMTP_PASS: ${param:SMTP_PASS, ''}
    CORS_ORIGIN: 'https://flux-erp-web.vercel.app'

build:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    target: node20
    external:
      - '@aws-sdk/*'

functions:
  api:
    handler: src/lambda.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY

plugins:
  - serverless-offline